### ISSUE TITLE
Add support for de- and encryption of secret in xyz-connector libs

### ISSUE THREAD

**Issue by jwegne** [heremaps/xyz-hub#59]
There is a need to store encrypted secrets in either space definitions or token metadata:

There already are several connectors that need credentials to access external resources. These credentials should not be stored as clear text with the connector's configuration within a space in order to prevent unauthorized access.

Since this functionality is already needed in several connectors today, we think it should be provided centrally as part of the XYZ infrastructure, especially since the number of affected connectors will likely rise in the future.

One possible way would be to implement this functionality inside XYZ hub so the credentials are decrypted when calling connectors that need them. The need for encryption and decryption might be signified by e.g. a prefix to field names within the connector configuration. This would be the most convenient way for connector developers. However, it has the potential to introduce significant overhead within XYZ hub which is not desirable. Additionally, great care would need to be taken in order to prevent accidental leaking of decrypted secrets during the (external) call to the connectors, e.g. by logging the request to the connector prior to sending it.

To us it is clear that the decryption process should take place inside the individual connectors. However, we think this should happen in a uniform way and would like to spare connector developers from having to implement decryption routines from scratch for every new connector.
First, getting it done right will prevent errors in the en- and decryption routines to leak credentials to the outside and second it will prevent developers writing the same boiler plate code over and over.

Therefore, we suggest to expand the xyz-connector libraries in order to add support for de- and encrypting secrets using asymmetric (public/private key) encryption. By utilizing a service like Amazon's KMS we can ensure that connector code does not get direct knowledge of the private key, thus enabling us to use a single, strong public/private key pair per environment for all connectors deployed there in order to keep things simple. Despite that, it would still be possible to use individual public/private key pairs for certain connectors if that requirement should arise.

Preliminary technical proposal for further discussion:

- We need to configure a private/public key pair. The public key is used for encrypting the secrets either by the users or the connector. The private key should only be accessible by the connector to decrypt the secrets.
 - The public key needs to be accessible - either in the documentation of XYZ Hub or there is an REST/HTTP call to get it.
- Add a new helper class to XYZ connectors lib that needs to know where to find the public/private key pair. We would suggest to use AWS KMS to store them. The helper class will have methods for en- and decryption the secrets.  If no public/private key pair is configured, the values will be returned as is.
- In ListenerConnector.java and ProcessorConnector.java we will check if the connector params, params or token metadata contain values that are enclosed in a certain pre- and postfix. We would suggest using "\<\<" and ">>".
 - If such values are found, the configured private key is used to decrypt the values and forward it to the custom connector implementation.
 - Automatic encryption using format ">>PLAINTEXT<<"
 - Automatic decryption using format "\<\<CYPHERTEXT>>"

**Comment by goshev** [comment]
Hi @jwegne,

Thanks for opening an issue for this feature request!

It is important to first try to avoid storing any secrets, such as database passwords and other, in your space configuration and retrieve them in a secure manner in your connectors instead.

As you pointed out correctly the Hub is not the right place add this functionality, and the decryption should take place in the individual connector. The Hub is agnostic about the parameter values for the connector and in the JWT token the metadata, and they are simply passed to the connector with the event.

Any encryption itself should take place on the client side. Otherwise unencrypted password and secrets will end up in logs and will be visible for listener, processor and storage connectors from other developers. Using one single private key shared by all connectors is similarly not possible solution, for the same reason.

The PSQL connector does not require this functionality, since it does not rely on any secrets stored in the space definition. Therefore I assume the feature request is then to add a reference implementation other connectors implemented in Java using the xyz-connectors library as a separate artifact. This should be for decryption only for the above mentioned reasons.

KMS is a good option, if you run your connector in AWS Lambda. The Hub however offers the possibility for generic HTTP connectors, since version 1.2.0, therefore a generic reference implementation should not rely on a cloud provider solution specifically. However it would be an option to provide different optional implementations.

As this is regarding only a reference implementation in the java connector library, I would consider it as a "nice to have" feature.
